title: Zack Sempsrott # your name (or website title) here
logo: "./images/IMG_4613_copy.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
<p> "Driven Junior Web Developer welcoming challenging projects and opportunities to learn. 
Focused on expanding knowledge and abilities in website design and development." </p>
 
  <br><br>
  <a href="https://www.linkedin.com/in/zack-sempsrott-a38851104/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
